# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0c9bbe820a068ce8cab3f9babe0d1849d731a0933dabd41931a1e30d4e9265354a9bf9b00f2f459839e8c7b4a3688d507795b1082316e9a482486e55dc13f6e

test:
  secret_key_base: af55fb505ed688144777957fe7b6d2a77d2636870fcaea5d13568efabb3ca3c4a4dbd87f21eb4c06f7d353f4183a4ca9b22544f68b5978d80529a78f0da7c5fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
